title: Milton Keynes Sex Addicts Anonymous
description: MK-SAA
# email: mksaa.recovery@gmail.com

# Temporary theme!
theme: minima
# Was: theme: jekyll-theme-slate

minima:
  skin: dark

plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

exclude:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - donate.md
  - greenbookstudy.md

header_pages:
  - index.md
  - addict.md
  - women.md
  - contact.md
  - find.md
  - links.md

paypal:
  # Anonymous Paypal pool link.
  pool_url: https://paypal.com/pools/c/8CvGXqxfZn#_.Anonymous
  # pool_url: https://bit.ly/0921mk7t
  # Non-anonymous Paypal link.
  me_url: https://paypal.me/Mkfellowship/%amount
  # me_url: https://paypal.me/Mkfellowship/5.00

# End.
